# Site settings
title: Kate Bennet
description: Product Designer
keywords: Design, Product, UX
author: Kate Bennet
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
